### ISSUE TITLE
Mascaras de telefone

### ISSUE THREAD

**Issue by CoutoDev** [the-it-nerd/magento-module-brasil#1]
Existem alguns locais tratando a mascara de telefone em um formato que não me parece com o padrão brasileiro. 

Exemplo de arquivo com esse formato de mascara:

https://github.com/the-it-nerd/magento-module-brasil/blob/f006eb4dc4e1b54e6c699ae1f6d35b2631cdcae9/view/frontend/templates/customer/address/masks.phtml#LL10C15-L10C38

Instalei o módulo para testar, e no front (checkout) o telefone fica assim:
![image](https://github.com/the-it-nerd/magento-module-brasil/assets/26583101/7c653028-4844-46c9-a9b3-5bab2d53b236)

Não deveria ser algo como [nessa resposta no SO](https://pt.stackoverflow.com/a/42242)?

**Comment by rqsakai** [comment]
@CoutoDev obrigado por abrir a issue, vamos avaliar e testar o modelo proposto para entender como podemos melhorar a experiência deste módulo.
