### ISSUE TITLE
Clicar no item de menu criado pelo módulo, não surte efeito.

### ISSUE THREAD

**Issue by CoutoDev** [the-it-nerd/magento-module-brasil#2]
Ao instalar o módulo e acessar o dashboard, um icone novo é criado no menu lateral. Porém ao clicar nele, nada acontece.
Era para ter algum redirecionamento? Talvez esteja herdando de `the_it_nerd/module-core`, mas sem configuração especifica pra esse módulo.

Segue vídeo do problema:
[theitnerd.webm](https://github.com/the-it-nerd/magento-module-brasil/assets/26583101/011eeb84-de2b-43ca-becd-c6e225a49e0b)

**Comment by rqsakai** [comment]
Couto obrigado pela abertura da issue, isso é esperado, o menu é criado pelo [módulo core](https://github.com/the-it-nerd/magento-module-core).

Este menu será usado para outros módulos como o de SEO e LGPD.
